import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";

import Header from "~/components/NavBar";
import MainContent from "~/components/MainContent";
import LeftSideBar from "~/components/LeftSideBar";

import { api } from "~/utils/api";

export default function Home() {
  const hello = api.post.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <link rel="icon" href="/dev.to.ico" />

        <title>Dev</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <div className="bg-gray-100">
        <Header />
        <div className="mx-2 flex min-h-screen flex-row bg-gray-100 sm:mx-2 md:mx-12">
          <div className="basis-2/12 max-sm:hidden">
            <LeftSideBar />
          </div>

          <div className="basis-full md:basis-7/12">
            <MainContent />
          </div>

          <div className="basis-3/12 max-md:hidden">
            <LeftSideBar />
          </div>
        </div>
      </div>
    </>
  );
}

function AuthShowcase() {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.post.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined },
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
}
