import Head from "next/head";

export default function Header() {
  return (
    <Head>
      <link rel="icon" href="/dev.ico" />

      <title>Dev</title>
      <meta name="description" content="Generated by create-t3-app" />
    </Head>
  );
}
